### PR TITLE
Issue "Parsing error of a json response"

### PR DESCRIPTION
**Pull request by michkinn**
Don't parse the json when the server send an object formatted in json

### CODE REVIEW

**Comment by django43ru** [comment]
response = jQuery.parseJSON(data);  ==> response = JSON.parse(JSON.stringify(data)); // temporary solving a problem)

**Comment by sconsult** [comment]
hi, we have taken over this project and will have it integrated within the next couple days

**Comment by imjared** [comment]
You're closing out the issue without a fix?

**Comment by sconsult** [comment]
the fix has been implemented, we are working thought a domain transfer and i cant release the fix until then, give it a couple days ;-)

**Pull request closed without merging**
